$PGs = "ALGAR_HOLDING-CULA3-VLAN3050",
"ANDRITZ-BACKUP-CULA3-VLAN3158",
"ASS-BRA-DIS-TOYOTA-BACKUP-CULA3-VLAN3165",
"CAMPOS FIALHO BACKUP 3507",
"CSC-BACKUP-CULA3-VLAN3086",
"CSC-BRASIL-BACKUP-CULA3-VLAN-3202",
"ELETRISOL-BACKUP-CULA3-VLAN3511",
"FASTMEDIC-BACKUP-CULA3-VLAN3173",
"FINI-BACKUP-CULA3-VLAN3197",
"FUBRAE-BACKUP-CULA3-VLAN3506",
"GCN-BACKUP-CULA3-VLAN3191",
"HOSPSAOLUCAS-BACKUP-CULA3-VLAN-3505",
"INDTEXTEISNAJAR-BACKUP-CULA3-VLAN-3297",
"INTERENG-BACKUP-CULA3-VLAN3294",
"KEEP-TRUE-BACKUP-CULA3-VLAN3178",
"LOS-GROBOS-BACKUP-CULA3-VLAN3047",
"MAXBOLT-BACKUP-CULA3-VLAN3298",
"NACIONAL-EXPRESSO-BACKUP-CULA3-VLAN3105",
"NOVATECNOLOGIA-BACKUP-CULA03-VLAN3245",
"NUCLEO-DA-FE-BACKUP-CULA3-VLAN3075",
"PLASTPARK-BACKUP-CULA3-VLAN3512",
"PROMOCAO DO ENSINO - BACKUP - VLAN3292",
"SEEDCORP-BACKUP-CULA3-VLAN3300",
"SGHBRASIL-BACKUP-CULA3-VLAN3041",
"SOCIEDADE-MUTUARIA-BACKUP-CULA3-VLAN3504",
"WIRELESS-BACKUP-CULA3-VLAN3290"


##No notepad, coloque o cursor na primeira linha, alt+shift+down até o final e coloca " em todas as linhas. Faz o memso no final
##No notepad também (Ctrl+h), coloca $ em Localizar e ", em sustituir por, marcando a opção expressões regulares

foreach($PG in $PGs){

Get-VDPortgroup -Name $PG | Remove-VDPortGroup -Confirm:$false

}







